/**
 * ────────────────────────────────────────────────────────────────────────────
 * TOOL RESPONSE SCHEMA v2
 * ────────────────────────────────────────────────────────────────────────────
 *
 * Every tool in the system returns a `ToolResponse`. The `kind` discriminant
 * tells the backend (stream parser, chat history mapper) and frontend exactly
 * what shape to expect — no nested if/else, no guessing.
 *
 * KIND          WHEN TO USE                               DB RECORD?
 * ─────────────────────────────────────────────────────────────────
 * "query"       Fast, small reads (balance, block info)   No
 * "transaction" Produces unsigned txns for user to sign   Yes (async)
 * "async"       Slow external fetch (CoinGecko, Twitter)  Yes (async)
 *
 * ─── ID Glossary ───
 * executionId : Unique per tool invocation. Used to:
 *               - track async data readiness in MongoDB
 *               - update transaction signing status
 *               - link frontend cards to backend records
 *
 * requestId   : Unique per user prompt. One prompt may trigger N tool
 *               invocations, all sharing the same requestId. Used to:
 *               - group related tool outputs on the frontend
 *               - batch-fetch all data for a single prompt
 *
 * toolCallId  : Assigned by LangGraph. Links an AIMessage's tool_call
 *               to the ToolMessage result. NOT generated by us — extracted
 *               in LlmService from the LangGraph event.
 * ────────────────────────────────────────────────────────────────────────────
 */

// ── Lifecycle enums ─────────────────────────────────────────────────────────

/** Tracks whether async data (external API) has arrived in MongoDB. */
export type DataLifecycle = "pending" | "completed" | "failed";

/** Tracks the signing/broadcast lifecycle of an unsigned transaction. */
export type TxLifecycle = "unsigned" | "pending" | "completed" | "failed";

// ── Per-kind response interfaces ────────────────────────────────────────────

/**
 * QUERY: lightweight, synchronous reads.
 * Data is returned inline (`data` field). No MongoDB record.
 *
 * Examples: get_balance, get_chain_info, get_token_info, get_block_by_number
 */
export interface QueryToolResponse<T = unknown> {
  kind: "query";
  executionId: string;
  toolName: string;
  requestId?: string;
  text: string;
  isError: false;
  data: T;
}

/**
 * TRANSACTION: produces unsigned transaction(s) for the user to sign.
 * Backend creates a MongoDB record (via createTransactionResponse)
 * so the frontend can poll/update signing status.
 * Actual unsigned transactions are stored in MongoDB, fetched by executionId.
 *
 * Examples: transfer_sei, transfer_token, place_order, wrap_sei, bridge
 */
export interface TransactionToolResponse {
  kind: "transaction";
  executionId: string;
  toolName: string;
  requestId?: string;
  text: string;
  isError: false;
}

/**
 * ASYNC: slow external data fetch. Returns immediately with `pending`,
 * data lands in MongoDB when ready, frontend polls or uses SSE.
 *
 * Examples: get_crypto_or_token_data, twitter tools, DCA simulation
 */
export interface AsyncToolResponse {
  kind: "async";
  executionId: string;
  toolName: string;
  requestId?: string;
  text: string;
  isError: false;
  dataType: string;
  dataStatus: DataLifecycle;
}

/**
 * ERROR: any tool that fails returns this.
 * `kind` is preserved so the frontend knows what was attempted.
 */
export interface ErrorToolResponse {
  kind: "query" | "transaction" | "async";
  executionId: string;
  toolName: string;
  requestId?: string;
  text: string;
  isError: true;
  errorCode?: string;
}

// ── Union type ──────────────────────────────────────────────────────────────

/** Every tool returns one of these. */
export type ToolResponse<T = unknown> =
  | QueryToolResponse<T>
  | TransactionToolResponse
  | AsyncToolResponse
  | ErrorToolResponse;

// ── Type guards ─────────────────────────────────────────────────────────────

export function isQueryResponse<T>(
  r: ToolResponse<T>,
): r is QueryToolResponse<T> {
  return r.kind === "query" && !r.isError;
}

export function isTransactionResponse(
  r: ToolResponse,
): r is TransactionToolResponse {
  return r.kind === "transaction" && !r.isError;
}

export function isAsyncResponse(r: ToolResponse): r is AsyncToolResponse {
  return r.kind === "async" && !r.isError;
}

export function isErrorResponse(r: ToolResponse): r is ErrorToolResponse {
  return r.isError === true;
}
